"""Bridge from codegen preview payloads to formal patch artifacts.

Converts spec-driven code generation output into patch queue-compatible format,
with mandatory behavioral test generation and governance-compliant routing.
"""

from __future__ import annotations

import hashlib
import json
import time
import zipfile
from pathlib import Path
from typing import Any

_PATCH_MANIFEST_NAME = "nova_patch.json"
_PLACEHOLDER_MARKERS = (
    "Preview-only artifact. Route through patch governance",
    "def build_preview() -> dict[str, str]:",
    "self.assertTrue(True",
)


def _artifact_is_placeholder(content: str) -> bool:
    text = str(content or "")
    if not text.strip():
        return True
    return any(marker in text for marker in _PLACEHOLDER_MARKERS)


def validate_codegen_preview(payload: object) -> tuple[bool, str, dict[str, Any]]:
    """Validate codegen preview payload structure and contract.
    
    Returns:
        (ok, reason, parsed_payload)
    """
    if not isinstance(payload, dict):
        return False, "invalid_payload_type", {}

    schema = str(payload.get("schema") or "").strip()
    status = str(payload.get("status") or "").strip()
    preview_only = bool(payload.get("preview_only", False))
    apply_allowed = bool(payload.get("apply_allowed", False))

    if schema != "nova.codegen.preview.v1":
        return False, "unknown_schema", {}
    if status != "preview":
        return False, "invalid_status", {}
    if not preview_only:
        return False, "not_preview_only", {}
    if apply_allowed:
        return False, "apply_already_allowed", {}

    spec = payload.get("spec")
    if not isinstance(spec, dict):
        return False, "spec_missing", {}
    spec_name = str(spec.get("name") or "").strip()
    spec_purpose = str(spec.get("purpose") or "").strip()
    file_count = int(spec.get("file_count", 0) or 0)

    if not spec_name or not spec_purpose or file_count <= 0:
        return False, "spec_incomplete", {}

    artifacts = payload.get("artifacts")
    if not isinstance(artifacts, list) or len(artifacts) != file_count:
        return False, "artifacts_mismatch", {}

    for i, artifact in enumerate(artifacts):
        if not isinstance(artifact, dict):
            return False, f"artifact_{i}_invalid_type", {}
        path = str(artifact.get("path") or "").strip()
        content = str(artifact.get("content") or "").strip()
        if not path or not content:
            return False, f"artifact_{i}_incomplete", {}
        if _artifact_is_placeholder(content):
            return False, f"artifact_{i}_placeholder", {}

    provenance = payload.get("provenance")
    if not isinstance(provenance, dict):
        return False, "provenance_missing", {}

    return True, "", dict(payload)


def _generate_test_file(
    spec_name: str,
    artifact_path: str,
    artifact_kind: str,
    *,
    artifact_content: str,
) -> str:
    """Generate a behavioral compile/import gate for a generated artifact."""
    base_name = "".join(part.title() for part in Path(artifact_path).stem.split("_") if part) or "Generated"
    kind_label = artifact_kind.lower()
    if artifact_path.endswith(".py"):
        escaped = json.dumps(artifact_content)
        return (
            f'"""Behavioral test for generated {spec_name} / {artifact_path}.\n\n'
            f"Generated by codegen_patch_bridge for kind={kind_label}.\n"
            f'"""\n'
            f"import ast\n"
            f"import unittest\n\n\n"
            f"SOURCE = {escaped}\n\n\n"
            f"class Test{base_name}Generated(unittest.TestCase):\n"
            f"    def test_generated_source_compiles(self):\n"
            f"        ast.parse(SOURCE)\n\n"
            f"    def test_generated_source_mentions_spec(self):\n"
            f"        self.assertIn({json.dumps(spec_name)}, SOURCE)\n\n\n"
            f"if __name__ == '__main__':\n"
            f"    unittest.main()\n"
        )
    return (
        f'"""Behavioral test for generated {spec_name} / {artifact_path}."""\n'
        f"import unittest\n\n\n"
        f"CONTENT = {json.dumps(artifact_content)}\n\n\n"
        f"class Test{base_name}Generated(unittest.TestCase):\n"
        f"    def test_generated_content_present(self):\n"
        f"        self.assertTrue(bool(str(CONTENT).strip()))\n\n\n"
        f"if __name__ == '__main__':\n"
        f"    unittest.main()\n"
    )


def bridge_codegen_to_patch(
    preview_payload: dict[str, Any],
    *,
    codegen_id: str = "",
    operator_id: str = "",
) -> dict[str, Any]:
    """Convert codegen preview to a formal patch artifact record.
    
    Args:
        preview_payload: Validated codegen preview output
        codegen_id: Generation run identifier (optional)
        operator_id: Operator making the bridge request (optional)
    
    Returns:
        Patch artifact record ready for patch queue ingestion
    """
    spec = preview_payload.get("spec") or {}
    spec_name = str(spec.get("name") or "codegen-spec")
    spec_purpose = str(spec.get("purpose") or "")
    artifacts = preview_payload.get("artifacts") or []
    provenance = preview_payload.get("provenance") or {}

    ts = time.time()
    ts_iso = time.strftime("%Y-%m-%dT%H:%M:%S", time.gmtime(ts))
    patch_id = f"codegen-{spec_name}-{int(ts * 1000) % 1000000:06d}"

    files_for_patch = []
    tests_for_patch = []

    for artifact in artifacts:
        artifact_path = str(artifact.get("path") or "")
        artifact_content = str(artifact.get("content") or "")
        artifact_kind = str(artifact.get("kind") or "module")
        files_for_patch.append(
            {
                "path": artifact_path,
                "kind": artifact_kind,
                "intent": str(artifact.get("intent") or ""),
                "content_length": len(artifact_content),
                "content_hash": hashlib.sha256(artifact_content.encode("utf-8")).hexdigest()[:16],
            }
        )

        test_filename = f"tests/test_{Path(artifact_path).stem}_generated.py"
        test_content = _generate_test_file(
            spec_name,
            artifact_path,
            artifact_kind,
            artifact_content=artifact_content,
        )
        tests_for_patch.append(
            {
                "path": test_filename,
                "kind": "test",
                "content": test_content,
                "content_length": len(test_content),
                "content_hash": hashlib.sha256(test_content.encode("utf-8")).hexdigest()[:16],
            }
        )

    manifest = {
        "schema": "nova.patch.manifest.v1",
        "patch_id": patch_id,
        "source": "codegen_bridge",
        "created_at": ts_iso,
        "spec_source": {
            "type": "codegen",
            "spec_name": spec_name,
            "spec_purpose": spec_purpose,
            "spec_file_count": len(artifacts),
            "codegen_run_id": str(codegen_id or ""),
        },
        "provenance": {
            "generator": str(provenance.get("generator") or "codegen_tool"),
            "model": str(provenance.get("model") or ""),
            "prompt_hash": str(provenance.get("prompt_hash") or ""),
            "bridge_operator": str(operator_id or "system"),
            "bridge_ts": ts_iso,
        },
        "files": files_for_patch,
        "tests": tests_for_patch,
        "governance": {
            "requires_behavioral_gate": True,
            "requires_operator_approval": True,
            "preview_only": True,
            "apply_allowed": False,
        },
    }

    bundle_files = []
    for artifact in artifacts:
        bundle_files.append(
            {
                "path": str(artifact.get("path") or ""),
                "content": str(artifact.get("content") or ""),
            }
        )
    for test in tests_for_patch:
        bundle_files.append(
            {
                "path": str(test.get("path") or ""),
                "content": str(test.get("content") or ""),
            }
        )

    return {
        "schema": "nova.patch.artifact.v1",
        "patch_id": patch_id,
        "status": "preview",
        "created_at": ts_iso,
        "spec_source": manifest["spec_source"],
        "provenance": manifest["provenance"],
        "manifest": manifest,
        "bundle_files": bundle_files,
        "file_count": len(files_for_patch),
        "test_count": len(tests_for_patch),
        "ready_for_behavioral_gate": True,
        "ready_for_patch_queue": True,
    }


def materialize_codegen_patch_zip(
    preview_payload: dict[str, Any],
    patch_artifact: dict[str, Any],
    *,
    updates_dir: Path,
    current_revision: int,
) -> Path:
    updates = Path(updates_dir)
    updates.mkdir(parents=True, exist_ok=True)
    patch_id = str(patch_artifact.get("patch_id") or "codegen-patch").strip() or "codegen-patch"
    ts = time.strftime("%Y%m%d_%H%M%S")
    zip_path = updates / f"codegen_{patch_id}_{ts}.zip"
    manifest = dict(patch_artifact.get("manifest") or {})
    manifest.setdefault("name", patch_id)
    manifest.setdefault("notes", "Codegen bridge materialized patch artifact.")
    manifest["patch_revision"] = int(manifest.get("patch_revision", current_revision + 1) or current_revision + 1)
    manifest["min_base_revision"] = int(manifest.get("min_base_revision", current_revision) or current_revision)
    manifest["preview_kind"] = "codegen_bridge"
    manifest["source"] = "codegen_bridge"

    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for item in list(patch_artifact.get("bundle_files") or []):
            if not isinstance(item, dict):
                continue
            path = str(item.get("path") or "").strip()
            content = str(item.get("content") or "")
            if not path:
                continue
            archive.writestr(path.replace("\\", "/"), content)
        archive.writestr(_PATCH_MANIFEST_NAME, json.dumps(manifest, ensure_ascii=True, indent=2) + "\n")
    return zip_path


def format_bridge_summary(
    preview_payload: dict[str, Any],
    patch_artifact: dict[str, Any],
) -> str:
    """Format a human-readable summary of bridge conversion.
    
    Args:
        preview_payload: Original codegen preview
        patch_artifact: Converted patch artifact
    
    Returns:
        Formatted summary string
    """
    spec = preview_payload.get("spec") or {}
    spec_name = str(spec.get("name") or "unknown")
    file_count = int(spec.get("file_count", 0) or 0)
    test_count = int(patch_artifact.get("test_count", 0) or 0)
    patch_id = str(patch_artifact.get("patch_id") or "unknown")

    return (
        f"Codegen Bridge Conversion Summary\n"
        f"=================================\n"
        f"Spec:          {spec_name}\n"
        f"Patch ID:      {patch_id}\n"
        f"Files:         {file_count}\n"
        f"Generated Tests: {test_count}\n"
        f"Status:        preview → patch queue\n"
        f"Next Step:     behavioral gate validation\n"
    )


CODEGEN_PATCH_BRIDGE_SERVICE = type(
    "CodegenPatchBridgeService",
    (),
    {
        "validate_codegen_preview": staticmethod(validate_codegen_preview),
        "bridge_codegen_to_patch": staticmethod(bridge_codegen_to_patch),
        "materialize_codegen_patch_zip": staticmethod(materialize_codegen_patch_zip),
        "format_bridge_summary": staticmethod(format_bridge_summary),
    },
)()
