from __future__ import annotations


COMPACT_REGRESSION_LANES: dict[str, list[str]] = {
    "unit": [
        "tests.test_health",
        "tests.test_installer_validation_service",
        "tests.test_smoke_test",
        "tests.test_action_planner",
        "tests.test_autonomy_execution_gate",
        "tests.test_autonomy_maintenance",
        "tests.test_autonomy_orchestrator_ledger_service",
        "tests.test_autonomy_orchestrator_service",
        "tests.test_behavior_metrics_service",
        "tests.test_chat_identity_service",
        "tests.test_control_actions_service",
        "tests.test_control_assets_service",
        "tests.test_control_auth_service",
        "tests.test_control_status_cache_service",
        "tests.test_control_status_service",
        "tests.test_control_status_surfaces_service",
        "tests.test_frontdoor_cli_parity_service",
        "tests.test_layer_maturity_policy_service",
        "tests.test_control_telemetry_service",
        "tests.test_core_steward_service",
        "tests.test_end_to_end_wiring_service",
        "tests.test_nova_temporal_service",
        "tests.test_temporal_review_tool",
        "tests.test_sock_service",
        "tests.test_evidence_validity",
        "tests.test_fulfillment_flow_service",
        "tests.test_http_session_store",
        "tests.test_http_test_session_helpers",
        "tests.test_identity_memory_service",
        "tests.test_memory_adapter_service",
        "tests.test_memory_health_service",
        "tests.test_memory_scope",
        "tests.test_nova_action_ledger_service",
        "tests.test_nova_control_action_dispatcher",
        "tests.test_nova_core_identity_context",
        "tests.test_nova_fulfillment_routing",
        "tests.test_nova_pulse_service",
        "tests.test_nova_reply_sequence",
        "tests.test_nova_route_probing",
        "tests.test_nova_runtime_context",
        "tests.test_nova_self_status_service",
        "tests.test_ollama_test_guard",
        "tests.test_patch_control_service",
        "tests.test_policy_control_service",
        "tests.test_policy_manager_resolver",
        "tests.test_policy_manager_service",
        "tests.test_nova_tool_policy_service",
        "tests.test_regression_contracts",
        "tests.test_release_status_service",
        "tests.test_release_runtime_truth_service",
        "tests.test_release_clean_service",
        "tests.test_run_regression",
        "tests.test_run_tools",
        "tests.test_runtime_artifacts_service",
        "tests.test_runtime_control_service",
        "tests.test_runtime_process_state_service",
        "tests.test_runtime_status_service",
        "tests.test_runtime_timeline_service",
        "tests.test_session_admin_service",
        "tests.test_session_state_service",
        "tests.test_smoke_placeholder",
        "tests.test_subconscious_control_service",
        "tests.test_supervisor_probes",
        "tests.test_supervisor_registry",
        "tests.test_test_session_control_service",
        "tests.test_tool_console_service",
        "tests.test_tool_execution_service",
        "tests.test_os_capability_operator_outbox_service",
        "tests.test_os_capability_registry_service",
        "tests.test_os_script_controller_service",
        "tests.test_tool_registry",
        "tests.test_tool_registry_service",
        "tests.test_validation_artifact_truth_service",
        "tests.test_voice_entrypoints",
        "tests.test_voice_interaction_service",
        "tests.test_regression_profile_inventory_service",
        "tests.test_test_profile_inventory_signal_service",
        "tests.test_web_research_session_service",
        "tests.test_server_side_runtime_service",
    ],
    "behavior": [
        "tests.test_http_chat_flow",
        "tests.test_http_session_manager",
        "tests.test_nova_core_fulfillment_bridge",
        "tests.test_nova_http",
        "tests.test_policy_commands",
        "tests.test_subconscious_fallback_seams",
        "tests.test_supervisor_ownership_gate",
        "tests.test_weather_behavior",
    ],
    "integration": [
        "tests.test_memory_capture.TestMemoryCapture.test_mem_add_and_recall",
        "tests.test_memory_cli",
        "tests.test_release_package_scripts",
        "tests.test_run_test_session",
        "tests.test_runtime_recovery",
        "tests.test_subconscious_live_simulator",
        "tests.test_subconscious_runner",
        "tests.test_windows_installer_scripts",
    ],
}


SOURCE_PROFILE_LANES: dict[str, list[str]] = {
    **COMPACT_REGRESSION_LANES,
    "source_data_pipelines": [
        "tests.test_control_pipelines_service",
        "tests.test_decision_pipeline",
        "tests.test_nova_http_pipeline_control",
        "tests.test_nova_pipeline_tools",
        "tests.test_pipeline_privileged_bridge",
        "tests.test_pipeline_privileged_protocol",
        "tests.test_pipeline_privileged_worker",
        "tests.test_pipeline_query_guard",
    ],
    "source_http_api_control": [
        "tests.test_control_status_surfaces_service",
        "tests.test_frontdoor_cli_parity_service",
        "tests.test_nova_http_autonomy_summary",
        "tests.test_nova_http_frontdoor",
        "tests.test_nova_http_generated_work",
        "tests.test_nova_http_get_routes",
        "tests.test_nova_http_grounded_self_report",
        "tests.test_nova_http_policy_search",
        "tests.test_nova_http_post_dispatch",
        "tests.test_nova_http_post_routes",
        "tests.test_nova_http_request_binding",
        "tests.test_nova_http_responses",
        "tests.test_nova_http_transport",
        "tests.test_nova_http_turn_finalization",
    ],
    "source_memory_identity": [
        "tests.test_memory_identity_bootstrap_service",
        "tests.test_memory_routing_service",
        "tests.test_memory_retention_service",
        "tests.test_edfi_core",
        "tests.test_leah_conversation_continuity",
        "tests.test_nova_memory_learning_service",
    ],
    "source_model_runtime": [
        "tests.test_nova_ollama_chat",
        "tests.test_ollama_health_service",
    ],
    "source_patch_pipeline": [
        "tests.test_nova_patching_service",
        "tests.test_nova_tool_dispatch",
    ],
    "source_generated_code": [
        "tests.test_capability_gap_detector",
        "tests.test_layer_maturity_policy_service",
        "tests.test_codegen_memory_recorder",
        "tests.test_codegen_patch_bridge",
        "tests.test_codegen_tool",
        "tests.test_orchestrator_codegen",
        "tests.test_patch_promotion_memory",
    ],
    "source_release": [
        "tests.test_installer_validation_service",
        "tests.test_release_promotion_judgment_service",
        "tests.test_release_runtime_truth_service",
        "tests.test_release_validation_service",
    ],
    "source_reply_quality_contracts": [
        "tests.test_intent_understanding",
        "tests.test_nova_fallback_flow",
    ],
    "source_runtime_core": [
        "tests.test_core_seam_guard_service",
        "tests.test_nova_core_guardrails",
        "tests.test_nova_guard_boot",
        "tests.test_nova_http_chat_runtime",
        "tests.test_operator_outbox_service",
        "tests.test_nova_reply_runtime",
        "tests.test_nova_vision_runtime",
        "tests.test_nova_voice_runtime",
        "tests.test_patch_guard",
        "tests.test_runtime_analytics_service",
        "tests.test_runtime_heartbeat_service",
        "tests.test_runtime_restart_provenance_service",
        "tests.test_supervisor_runtime",
        "tests.test_server_side_runtime_service",
    ],
    "source_subconscious": [
        "tests.test_subconscious_review_authority_service",
        "tests.test_subconscious_review_judgment_service",
        "tests.test_subconscious_route_probe",
        "tests.test_subconscious_training_backlog",
    ],
    "source_source_root_inventory": [
        "tests.test_end_to_end_wiring_service",
        "tests.test_nova_wiring_inventory_service",
        "tests.test_source_root_inventory_service",
        "tests.test_source_root_judgment_service",
    ],
    "source_test_ecosystem": [
        "tests.test_core_health_brief_service",
        "tests.test_core_thinning_service",
        "tests.test_evidence_validity",
        "tests.test_health_check_script",
        "tests.test_kidney",
        "tests.test_nova_action_ledger_helpers",
        "tests.test_nova_cli_delivery",
        "tests.test_nova_cli_sequence",
        "tests.test_nova_frontdoor_script",
        "tests.test_nova_grounded_self_report_service",
        "tests.test_nova_knowledge_packs",
        "tests.test_nova_location_weather_service",
        "tests.test_nova_reflection_health_service",
        "tests.test_nova_routing_helpers",
        "tests.test_nova_routing_support",
        "tests.test_sock_service",
        "tests.test_nova_session_state_service",
        "tests.test_nova_wiring_inventory_service",
        "tests.test_operator_control_service",
        "tests.test_ops_journal",
        "tests.test_planner_contract_service",
        "tests.test_planner_decision",
        "tests.test_port_ownership_service",
        "tests.test_safety_envelope",
        "tests.test_schedule_registry",
        "tests.test_smoke_e2e_script",
        "tests.test_source_root_inventory_service",
        "tests.test_storage_watch_service",
        "tests.test_teach_flow",
    ],
    "source_tool_registry_policy": [
        "tests.test_os_capability_operator_outbox_service",
    ],
    "source_web_search": [
        "tests.test_nova_search_endpoint",
        "tests.test_nova_tool_policy_service",
        "tests.test_nova_web_tools_service",
    ],
    "source_work_tree": [
        "tests.test_control_work_trees_service",
        "tests.test_subconscious_work_tree_triage_service",
        "tests.test_work_tree",
        "tests.test_work_tree_decision_adapter",
        "tests.test_work_tree_seeding_service",
        "tests.test_work_tree_signal_ingestion_service",
    ],
}
